# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  matekx_config = debug
  exprx_config = debug
  arger_config = debug
endif
ifeq ($(config),release)
  matekx_config = release
  exprx_config = release
  arger_config = release
endif

PROJECTS := matekx exprx arger

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

matekx:
ifneq (,$(matekx_config))
	@echo "==== Building matekx ($(matekx_config)) ===="
	@${MAKE} --no-print-directory -C . -f matekx.make config=$(matekx_config)
endif

exprx: matekx
ifneq (,$(exprx_config))
	@echo "==== Building exprx ($(exprx_config)) ===="
	@${MAKE} --no-print-directory -C . -f exprx.make config=$(exprx_config)
endif

arger: matekx
ifneq (,$(arger_config))
	@echo "==== Building arger ($(arger_config)) ===="
	@${MAKE} --no-print-directory -C . -f arger.make config=$(arger_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f matekx.make clean
	@${MAKE} --no-print-directory -C . -f exprx.make clean
	@${MAKE} --no-print-directory -C . -f arger.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   matekx"
	@echo "   exprx"
	@echo "   arger"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"